Repository cfug/dio, pull requests merged in 2022-01, with the labels that each got.

#1365 Fix section about request method aliases in readme
  README-ZH.md
  README.md
  dio/README-ZH.md
  dio/README.md
Labels: docs

#1367 Make `ResponseBody.statusCode` non-nullable
  dio/CHANGELOG.md
  dio/lib/src/adapter.dart
  dio/lib/src/adapters/browser_adapter.dart
Labels: enhancement

#1379 [ci] Add wildcard develop branches to workflows
  .github/workflows/dio.yml
  .github/workflows/example-app.yml
  .github/workflows/example.yml
  .github/workflows/plugin_cookie_manager.yml
  .github/workflows/plugin_http2_adapter.yml
Labels: enhancement

#1374 Type improvements
  .github/workflows/dio.yml
  .github/workflows/example-app.yml
  .github/workflows/example.yml
  .github/workflows/plugin_cookie_manager.yml
  .github/workflows/plugin_http2_adapter.yml
  dio/README-ZH.md
  dio/README.md
  dio/analysis_options.yaml
  dio/lib/src/adapter.dart
  dio/lib/src/adapters/browser_adapter.dart
  dio/lib/src/adapters/io_adapter.dart
  dio/lib/src/dio.dart
  dio/lib/src/dio_error.dart
  dio/lib/src/dio_mixin.dart
  dio/lib/src/entry/dio_for_native.dart
  dio/lib/src/form_data.dart
  dio/lib/src/headers.dart
  dio/lib/src/interceptor.dart
  dio/lib/src/options.dart
  dio/lib/src/response.dart
  dio/lib/src/transformer.dart
  dio/test/echo_adapter.dart
  dio/test/encoding_test.dart
  dio/test/interceptor_test.dart
  dio/test/mock_adapter.dart
  dio/test/readtimeout_test.dart
  example/lib/formdata.dart
  example/lib/http2_adapter.dart
  example/lib/response_interceptor.dart
  plugins/cookie_manager/analysis_options.yaml
  plugins/cookie_manager/example/example.dart
  plugins/cookie_manager/lib/src/cookie_mgr.dart
  plugins/cookie_manager/test/basic_test.dart
  plugins/http2_adapter/analysis_options.yaml
  plugins/http2_adapter/lib/src/http2_adapter.dart
  plugins/http2_adapter/test/http2_test.dart
Labels: enhancement

#1376 Various timeout parameter replaced with durations instead of ints
  README-ZH.md
  README.md
  dio/README-ZH.md
  dio/README.md
  dio/lib/src/adapters/browser_adapter.dart
  dio/lib/src/adapters/io_adapter.dart
  dio/lib/src/entry/dio_for_native.dart
  dio/lib/src/options.dart
  dio/test/download_test.dart
  dio/test/options_test.dart
  dio/test/readtimeout_test.dart
  dio/test/request_test.dart
  example/lib/dio.dart
  example/lib/download.dart
  example/lib/http2_adapter.dart
  example/lib/options.dart
  example/lib/post_stream_and_bytes.dart
  example/lib/request_interceptors.dart
  example_flutter_app/lib/routes/request.dart
  plugins/http2_adapter/example/example.dart
  plugins/http2_adapter/lib/src/connection_manager.dart
  plugins/http2_adapter/lib/src/connection_manager_imp.dart
  plugins/http2_adapter/test/http2_test.dart
Labels: enhancement

#1366 Make it possible to instantiate a universal adapter
  dio/CHANGELOG.md
  dio/README.md
  dio/lib/src/adapter.dart
  dio/lib/src/adapters/universal_adapter.dart
  dio/test/echo_adapter.dart
  dio/test/mock_adapter.dart
  example/lib/adapter.dart
  plugins/http2_adapter/lib/src/http2_adapter.dart
Labels: enhancement

#1393 fix: Only delete file when it exists
  dio/CHANGELOG.md
  dio/lib/src/entry/dio_for_native.dart
Labels: bug
