Repository cfug/dio, pull requests merged in 2023-03, with the labels that each got.

#1731 Document that interceptors aren't triggered by redirects
  dio/lib/src/interceptor.dart
Labels: e: documentation

#1757 [dio] Fix FormData encoding regression for maps with dynamic keys
  dio/CHANGELOG.md
  dio/lib/src/utils.dart
  dio/test/basic_test.dart
  dio/test/browser_test.dart
  dio/test/formdata_test.dart
  dio/test/utils.dart
Labels: b: regression

#1722 [dio] Fix missing source stacktrace in DioError
  .gitignore
  .idea/dio.iml
  dio/CHANGELOG.md
  dio/lib/src/adapters/io_adapter.dart
  dio/lib/src/cancel_token.dart
  dio/lib/src/dio/dio_for_native.dart
  dio/lib/src/dio_error.dart
  dio/lib/src/dio_mixin.dart
  dio/lib/src/options.dart
  dio/pubspec.yaml
  dio/test/cancel_token_test.dart
  dio/test/dio_mixin_test.dart
  dio/test/mock/http_mock.dart
  dio/test/mock/http_mock.mocks.dart
  dio/test/stacktrace_test.dart
Labels: b: regression

#1386 [http2_adapter] HTTP/2 proxy
  .github/workflows/tests.yml
  plugins/http2_adapter/CHANGELOG.md
  plugins/http2_adapter/README.md
  plugins/http2_adapter/example/example.dart
  plugins/http2_adapter/lib/src/client_setting.dart
  plugins/http2_adapter/lib/src/connection_manager_imp.dart
  plugins/http2_adapter/test/http2_test.dart
Labels: s: feature

#1771 [dio] Fix wrong default encoding being used for lists
  dio/CHANGELOG.md
  dio/lib/src/transformers/sync_transformer.dart
  dio/lib/src/utils.dart
  dio/test/encoding_test.dart
  dio/test/url_encoded_test.dart
Labels: p: dio, b: regression
