Repository cfug/dio, pull requests merged in 2023-09, with the labels that each got.

#1946 [http2_adapter] Fix redirect not working
  plugins/http2_adapter/CHANGELOG.md
  plugins/http2_adapter/lib/src/http2_adapter.dart
  plugins/http2_adapter/test/http2_test.dart
Labels: p: http2_adapter

#1898 👷 Melos
  .idea/modules.xml
  dio/.gitignore
  dio/melos_dio.iml
  example/pubspec_overrides.yaml
  example_flutter_app/pubspec_overrides.yaml
  melos.yaml
  melos_dio.iml
  plugins/cookie_manager/.gitignore
  plugins/cookie_manager/melos_dio_cookie_manager.iml
  plugins/cookie_manager/pubspec_overrides.yaml
  plugins/http2_adapter/.gitignore
  plugins/http2_adapter/melos_dio_http2_adapter.iml
  plugins/http2_adapter/pubspec_overrides.yaml
  plugins/native_dio_adapter/.gitignore
  plugins/native_dio_adapter/melos_native_dio_adapter.iml
  plugins/native_dio_adapter/pubspec_overrides.yaml
  pubspec.yaml
Labels: infra

#1956 Extend the bug template with OS multiselect
  .github/ISSUE_TEMPLATE/bug.yml
Labels: infra

#1962 Replace the install section in READMEs with link to pub.dev/install
  dio/README-ZH.md
  dio/README.md
  plugins/cookie_manager/README.md
  plugins/http2_adapter/README.md
  plugins/native_dio_adapter/README.md
Labels: e: documentation

#1955 Reduce cases in which browsers would trigger a CORS preflight request
  .github/workflows/tests.yml
  dio/CHANGELOG.md
  dio/dart_test.yaml
  dio/lib/src/adapters/browser_adapter.dart
  dio/test/request_integration_test.dart
  dio/test/utils.dart
Labels: p: dio, platform: web

#1977 👷 Add `README.md` & `CHANGELOG.md` size check for publishable tests
  .github/workflows/publishable.yml
  dio/CHANGELOG.md
Labels: infra

#1971 Improve docs for LogInterceptor
  dio/README-ZH.md
  dio/README.md
  dio/lib/src/interceptors/log.dart
Labels: e: documentation, p: dio
